services:
  pgsqldb:
    image: postgres:14.3
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data

  redis:
    image: redis
    environment:
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASS}
    

volumes:
  pgsqldata:
